#!/usr/bin/env node
import cp from 'child_process';
import path from 'path';

const bin = 'node';

const args = [
    '--no-warnings',
    '--experimental-strip-types',
    path.join(import.meta.dirname, 'bin', 'cli.js'),
    ...process.argv.slice(2),
];


cp.spawn(bin, args, {
    stdio: 'inherit',
    shell: true,
});
