#!/usr/bin/env node
import cp from 'child_process';
import path from 'path';

const bin = 'node';

const args = [
    '--no-warnings',
    '--experimental-strip-types',
    path.join(import.meta.dirname, 'console', 'index.js'),
    ...process.argv.slice(2),
];

const child = cp.spawn(bin, args, {
    stdio: 'inherit',
    // shell: true,
});

function killChild() {
    if (child && !child.killed) {
        child.kill('SIGTERM');
    }
}

process.on('SIGINT', () => {
    killChild();
    process.exit(0);
});

process.on('SIGTERM', () => {
    killChild();
    process.exit(0);
});

process.on('exit', () => {
    killChild();
});