# sample of how to run Zenith with Docker Compose
services:
    app:
        image: sidekickcoder/zenith:dev
        build: .
        ports:
            - 3001:3000
        # volumes:
        #     - ./.volumes/app/data:/data
        #     - ./.volumes/app/config:/app/config
        #     - ./.volumes/app/modules:/app/modules
        #     - ./.volumes/app/storage:/app/storage
        command:
            # - "@logger:level=debug"

            - "@config:database.default=memory"
            - "@config:database.migrator.auto=true"

            # auto-create users
            - "@config:users_auto=true"
            - "@config:users[1].username=${ZENITH_ADMIN_USERNAME:-admin}"
            - "@config:users[1].email=${ZENITH_ADMIN_EMAIL:-admin@dev.com}"
            - "@config:users[1].password=${ZENITH_ADMIN_PASSWORD:-admin-123}"
            - "@config:users[1].permissions=admin"

            # - "@config:plugins.downloads[0].repository=https://github.com/sidekick-coder/zenith-backup.git"
            # - "@config:plugins.downloads[0].destination=/app/plugins/zenith-backup"
            # - "@config:plugins.registry.01KRKSDD5BFHDMCKKD2C53DGBA.version_channel=branch:main"
            # - "@config:zbackups.plans.daily.name=daily"
            #
            #
