import { defineTheme } from '#client/composables/defineTheme.ts'

export default defineTheme({
    background: '#eff1f5',
    foreground: '#4c4f69',
    card: '#e6e9ef',
    'card-foreground': '#4c4f69',
    popover: '#e6e9ef',
    'popover-foreground': '#4c4f69',
    primary: '#8839ef',
    'primary-foreground': '#eff1f5',
    secondary: '#dce0e8',
    'secondary-foreground': '#4c4f69',
    muted: '#dce0e8',
    'muted-foreground': '#7c7f93',
    accent: '#ccd0da',
    'accent-foreground': '#4c4f69',
    destructive: '#d20f39',
    'destructive-foreground': '#eff1f5',
    border: '#bcc0cc',
    input: '#bcc0cc',
    ring: '#8839ef',
    'chart-1': '#8839ef',
    'chart-2': '#1e66f5',
    'chart-3': '#40a02b',
    'chart-4': '#df8e1d',
    'chart-5': '#ea76cb',
    sidebar: '#e6e9ef',
    'sidebar-foreground': '#4c4f69',
    'sidebar-primary': '#8839ef',
    'sidebar-primary-foreground': '#eff1f5',
    'sidebar-accent': '#ccd0da',
    'sidebar-accent-foreground': '#4c4f69',
    'sidebar-border': '#bcc0cc',
    'sidebar-ring': '#8839ef',
})
