import fs from 'fs'
import { basePath } from '@sidekick-coder/zenith-kit/server'
import di from '#server/facades/di.facade.ts'
import LifecycleHook from '#shared/entities/lifecycleHook.entity.ts'
import modules from '#server/facades/modules.facade.ts'
import type Module from '#shared/entities/module.entity.ts'
import ViteService from '#server/services/vite.service.ts'
import type { ViteServiceEvents } from '#server/services/vite.service.ts'
import env from '#server/facades/env.facade.ts'

export default class ModulesClientLifecycleHook extends LifecycleHook {
    public order = 5
    public mods: (Module & LifecycleHook)[] = []

    public async onRegister(): Promise<void> {
        // create client file to use on development 
        if (!env.development) return

        let content = '// This file is auto-generated by ModulesClientLifecycleHook, do not edit\n\n'

        content += 'export default {\n'

        content += '    // modules\n'

        for (const mod of modules.mods) {
            if (!mod.enabled) {
                continue
            }

            const clientPath = mod.findClientEntrypointFilename()

            if (!clientPath) {
                continue
            }

            content += `    '${mod.id}': () => import('${clientPath}'),\n`

        }

        content += '}\n\n'

        fs.mkdirSync(basePath('client/.runtime'), { recursive: true })
        fs.writeFileSync(basePath('client/.runtime/modules.ts'), content)
    }

    public async onLoad(): Promise<void> {
        const vite = di.get<ViteService>(ViteService)

        const mods = [] as any[]
        const assets = [] as any[]

        for (const mod of modules.mods) {
            if (!mod.enabled) {
                continue
            }

            const clientPath = mod.findClientEntrypointFilename()

            if (clientPath) {
                mods.push(mod)
            }

            // load assets if have
            if (env.production && fs.existsSync(mod.makePath('client-dist/browser/styles.css'))) {
                assets.push(`static/modules/${mod.id}/browser/styles.css`)
            }
        }

        vite.addDependency('modules', mods)

        vite.on('vite:render', ({ head }: ViteServiceEvents['vite:render']) => {
            assets.forEach(asset => {
                if (asset.endsWith('.css')) {
                    head
                        .child('link')
                        .attr('type', 'text/css')
                        .attr('rel', 'stylesheet')
                        .attr('href', `/${asset}`)
                }
            })
        })
    }

    public async onBoot(): Promise<void> { }
}
