import fs from 'fs'
import path from 'path'
import { basePath } from '@sidekick-coder/zenith-kit/server'
import di from '#server/facades/di.facade.ts'
import LifecycleHook from '#shared/entities/lifecycleHook.entity.ts'
import modules from '#server/facades/modules.facade.ts'
import type Module from '#shared/entities/module.entity.ts'
// import ViteService from '#server/services/vite.service.ts'
import type { ViteServiceEvents } from '#server/services/vite.service.ts'
import env from '#server/facades/env.facade.ts'

export default class ModulesClientLifecycleHook extends LifecycleHook {
    public order = 5
    public mods: (Module & LifecycleHook)[] = []

    public async onRegister(): Promise<void> {
        // create client file to use on development 
        if (!env.development) return

        // create a file for each client module
        for (const mod of modules.mods) {
            if (!mod.enabled) {
                continue
            }

            const clientPath = mod.findClientEntrypointFilename('dev')

            if (!clientPath) {
                continue
            }

            const filename = basePath('client/.modules', `${mod.id}.ts`)

            let content = '// This file is auto-generated by ModulesClientLifecycleHook, do not edit\n\n'

            content += 'export default async function() {\n'
            content += `    return import('${clientPath}')\n`
            content += '}\n\n'

            fs.writeFileSync(filename, content)
        }
    }

    public async onLoad(): Promise<void> {
        // const vite = di.get<ViteService>(ViteService)

        const mods = [] as any[]
        const assets = [] as any[]

        for (const mod of modules.mods) {
            if (!mod.enabled) {
                continue
            }

            const data: any = mod

            const devEntrypoint = mod.findClientEntrypointFilename('dev')
            const nodeEntrypoint = mod.findClientEntrypointFilename('node')
            const browserEntrypoint = mod.findClientEntrypointFilename('browser')

            data.entrypoints = {}

            if (devEntrypoint) {
                data.entrypoints.dev = devEntrypoint
            }

            if (nodeEntrypoint) {
                data.entrypoints.node = nodeEntrypoint
            }

            if (browserEntrypoint) {
                data.entrypoints.browser = `/static/modules/${mod.id}/browser/` + path.basename(browserEntrypoint)
            }

            mods.push(data)

            // load assets if have
            if (env.production && fs.existsSync(mod.makePath('client-dist/browser/styles.css'))) {
                assets.push(`static/modules/${mod.id}/browser/styles.css`)
            }
        }

        const clientModules = mods.map((mod: any) => ({
            id: mod.id,
            name: mod.name,
            enabled: mod.enabled,
            description: mod.description,
            version: mod.version,
            entrypoints: mod.entrypoints
        }))

        // vite.addDependency('modules', clientModules)
        //
        // vite.on('vite:render', ({ head }: ViteServiceEvents['vite:render']) => {
        //     assets.forEach(asset => {
        //         if (asset.endsWith('.css')) {
        //             head
        //                 .child('link')
        //                 .attr('type', 'text/css')
        //                 .attr('rel', 'stylesheet')
        //                 .attr('href', `/${asset}`)
        //         }
        //     })
        // })
    }

    public async onShutdown(): Promise<void> {
        // remove all files
        if (!env.development) return

        for (const mod of modules.mods) {
            const filename = basePath('client/.modules', `${mod.id}.ts`)

            if (fs.existsSync(filename)) {
                fs.unlinkSync(filename)
            }
        }
    }
}
