import fs from 'fs'
import { basePath, migrator, PluginEntity, PluginEntryEntity, SeederService, container, MigratorService } from '@sidekick-coder/zenith-kit/server'
import type { EventContract } from '@sidekick-coder/zenith-kit/server'
import PluginLoaderService from './PluginLoaderService.ts'
import emmitter from '#server/facades/emmitter.facade.ts'
import seeder from '#server/facades/seeder.facade.ts'

export default class PluginLoaderDevelopmentService extends PluginLoaderService {
    private async onBeforeCliLoad({ cli }: EventContract['cli:before-load']) {
        for (const plugin of this.entries.values()) {
            if (!plugin.enabled) continue

            const commandsFolder = plugin.makePath('src', 'server', 'commands')

            if (!fs.existsSync(commandsFolder)) {
                continue
            }

            cli.addDir(commandsFolder)
        }
    }

    private async onMigratorRegistered({ migrator }: EventContract['migrator:loaded']) {
        const entries = Array.from(this.entries.values()).filter(plugin => plugin.enabled)

        for (const plugin of entries) {
            const logger = this.logger.child({ pluginId: plugin.id })

            migrator.addSource({
                id: plugin.id,
                directory: plugin.makePath('src', 'server', 'migrations'),
            })

            if (this.debug) {
                logger.debug(`added plugin ${plugin.id} migrations to migrator`)
            }
        }
    }

    private async onSeederRegistered({ seeder }: EventContract['seeder:loaded']) {
        const entries = Array.from(this.entries.values()).filter(plugin => plugin.enabled)

        for (const plugin of entries) {
            const logger = this.logger.child({ pluginId: plugin.id })

            seeder.addSource({
                id: plugin.id,
                directory: plugin.makePath('src', 'server', 'seeders'),
            })

            if (this.debug) {
                logger.debug(`added plugin ${plugin.id} seeders to seeder`)
            }

        }
    }

    private async loadPluginServerEntry(plugin: PluginEntryEntity) {
        const logger = this.logger.child({ pluginId: plugin.id })

        const entry = plugin.makePath('src', 'server', 'index.ts')

        if (!fs.existsSync(entry)) {
            logger.warn(`${plugin.id} server entry not found, skipping...`)
            return
        }

        let contructor = await import(entry)

        contructor = contructor.default || contructor

        if (typeof contructor !== 'function') {
            logger.error(`default export of plugin ${plugin.id} is not a constructor function`)
            return
        }

        if (!contructor.fromPluginDiscoverEntity) {
            logger.error(`looks like plugin ${plugin.id} is not a instance of PluginEntity`)
            return
        }

        const instance: PluginEntity = contructor.fromPluginDiscoverEntity(plugin)

        await instance.load()

        if (this.debug) {
            logger.debug(`loaded plugin (${plugin.id} v${instance.version})`)
        }
    }

    public async loadServerPLugins(): Promise<void> {
        const plugins = Array.from(this.entries.values()).filter(plugin => plugin.enabled)

        for (const plugin of plugins) {
            await this.loadPluginServerEntry(plugin)
        }
    }

    public async loadClientPLugin(): Promise<void> {
        const plugins = Array.from(this.entries.values()).filter(plugin => plugin.enabled)

        const entries = [] as any

        for (const plugin of plugins) {
            const logger = this.logger.child({ pluginId: plugin.id })

            const entry = plugin.makePath('src', 'client', 'index.ts')

            if (!fs.existsSync(entry)) {
                logger.warn(`${plugin.id} client entry not found, skipping...`)
                return
            }

            const filename = basePath('client/.plugins', `${plugin.id}.ts`)

            let content = '// This file is auto-generated by ModulesClientLifecycleHook, do not edit\n\n'

            content += 'export default async function() {\n'
            content += `    return import('${entry}')\n`
            content += '}\n\n'

            fs.writeFileSync(filename, content)

            if (this.debug) {
                logger.debug(`write temporary file plugin entry for plugin ${plugin.id}`, { filename, })
            }

            entries.push({
                id: plugin.id,
                name: plugin.name,
                version: plugin.version,
                enabled: plugin.enabled,
            })
        }

        emmitter.on('page:request:start', ctx => {
            ctx.setContainerValue('plugin:entries', entries)
        })
    }


    public async load(): Promise<void> {
        await this.loadServerPLugins()
        await this.loadClientPLugin()

        emmitter.on('cli:before-load', this.onBeforeCliLoad.bind(this))

        emmitter.on('migrator:registered', this.onMigratorRegistered.bind(this))
        emmitter.on('seeder:registered', this.onSeederRegistered.bind(this))
    }

    public async cleanup(): Promise<void> {
        const files = await fs.promises.readdir(basePath('client/.plugins'))

        const pluginFiles = files.filter(file => file.endsWith('.ts'))

        for (const file of pluginFiles) {
            await fs.promises.unlink(basePath('client/.plugins', file))
        }
    }
}
