import fs from 'fs'
import { basePath, migrator, PluginEntity, PluginEntryEntity } from '@sidekick-coder/zenith-kit/server'
import PluginManagerService from './PluginManagerService.ts'
import emmitter from '#server/facades/emmitter.facade.ts'

export default class PluginManagerDevelopmentService extends PluginManagerService {
    private async loadPluginServerEntry(plugin: PluginEntryEntity) {
        const logger = this.logger.child({ pluginId: plugin.id })

        const entry = plugin.makePath('src', 'server', 'index.ts')

        if (!fs.existsSync(entry)) {
            logger.warn(`${plugin.id} server entry not found, skipping...`)
            return
        }

        let contructor = await import(entry)

        contructor = contructor.default || contructor

        if (typeof contructor !== 'function') {
            logger.error(`default export of plugin ${plugin.id} is not a constructor function`)
            return
        }

        if (!contructor.fromPluginDiscoverEntity) {
            logger.error(`looks like plugin ${plugin.id} is not a instance of PluginEntity`)
            return
        }

        const instance: PluginEntity = contructor.fromPluginDiscoverEntity(plugin)

        await instance.load()

        if (plugin.makePath('src', 'server', 'migrations')) {
            migrator.addSource({
                id: plugin.id,
                directory: plugin.makePath('src', 'server', 'migrations'),
            })

            if (this.debug) {
                logger.debug(`added plugin ${plugin.id} migrations to migrator`)
            }
        }

        if (this.debug) {
            logger.debug(`loaded plugin (${plugin.id} v${instance.version})`)
        }
    }

    public async loadServerPLugins(): Promise<void> {
        const plugins = Array.from(this.entries.values()).filter(plugin => plugin.enabled)

        for (const plugin of plugins) {
            await this.loadPluginServerEntry(plugin)
        }
    }

    public async loadClientPLugin(): Promise<void> {
        const plugins = Array.from(this.entries.values()).filter(plugin => plugin.enabled)

        const entries = [] as any

        for (const plugin of plugins) {
            const logger = this.logger.child({ pluginId: plugin.id })

            const entry = plugin.makePath('src', 'client', 'index.ts')

            if (!fs.existsSync(entry)) {
                logger.warn(`${plugin.id} client entry not found, skipping...`)
                return
            }

            const filename = basePath('client/.plugins', `${plugin.id}.ts`)

            let content = '// This file is auto-generated by ModulesClientLifecycleHook, do not edit\n\n'

            content += 'export default async function() {\n'
            content += `    return import('${entry}')\n`
            content += '}\n\n'

            fs.writeFileSync(filename, content)

            if (this.debug) {
                logger.debug(`write temporary file plugin entry for plugin ${plugin.id}`, { filename, })
            }

            entries.push({
                id: plugin.id,
                name: plugin.name,
                version: plugin.version,
                enabled: plugin.enabled,
            })
        }

        emmitter.on('page:request:start', ctx => {
            ctx.setContainerValue('plugin:entries', entries)
        })
    }


    public async load(): Promise<void> {
        await this.loadServerPLugins()
        await this.loadClientPLugin()
    }

    public async cleanup(): Promise<void> {
        const files = await fs.promises.readdir(basePath('client/.plugins'))

        const plguinFiles = files.filter(file => file.endsWith('.ts'))

        for (const file of plguinFiles) {
            await fs.promises.unlink(basePath('client/.plugins', file))
        }
    }
}
