# sample of how to run Zenith with Docker Compose
services:
    app:
        image: zzhenryquezz/zenith:0.0.3
        restart: unless-stopped
        ports:
            - 3003:3000
        volumes:
            - .volumes/app/modules:/app/modules
            - .volumes/app/storage:/app/storage
        environment:
            APP_URL: http://localhost:3003
